# TODO kubernetes/swarm => docker stack deploy --compose-file docker-compose.yml
# Deploy influxdb + mongodb
# https://docs.docker.com/engine/reference/commandline/stack_deploy/#examples
version: '3.3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
  influx:
    image: influxdb:alpine
    container_name: influxdb
    ports:
      - '8086:8086'
    restart: always
    #volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      #- /srv/docker/influxdb/data:/var/lib/influxdb
    #configs:
    #  - source: influx_config
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3001:3000'
    restart: always
configs:
  influx_config:
    file: ./influx/influxdb.conf
