# Deploy grafana + influxdb + mongodb
version: '3.3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
  influx:
    image: influxdb:1.8
    container_name: influxdb
    volumes:
      - /srv/docker/influxdb/data:/var/lib/influxdb
      - ./influx/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      #- ./influx/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - '8086:8086'
      - '8088:8088'
    restart: always
  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
      - '3001:3000'
    restart: always
